name: Check Spelling
on:
  pull_request:
    paths:
    - '**.md'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        ref: ${{ github.head_ref }}
